version: "3"

services:
  web:
    build:
      context: .
      dockerfile: build/web.Dockerfile
    environment:
      - "NODE_PATH=/app/node_modules/"
      - "ENVIRONMENT=${ENVIRONMENT}"
      - "PORT=${PORT}"
      - "TSCW_RELAY_TOKEN=${TSCW_RELAY_TOKEN}"
    ports:
      - 2469:2469
    restart: always
